name: Build RootHide deb

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl xz-utils fakeroot dpkg-dev

      - name: Install Theos
        run: |
          export THEOS=$HOME/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Install iPhoneOS SDK
        run: |
          export THEOS=$HOME/theos

          mkdir -p $THEOS/sdks

          if [ -z "$(ls -A $THEOS/sdks)" ]; then
            git clone --depth=1 https://github.com/theos/sdks.git $THEOS/sdks
          else
            echo "SDK already exists"
          fi

      - name: Build package
        run: |
          export THEOS=$HOME/theos
          make clean
          make package FINALPACKAGE=1

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: SB-CPU-Floating-deb
          path: packages/*.deb
