name: Build RootHide deb

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl xz-utils fakeroot dpkg-dev

      - name: Install Theos
        run: |
          export THEOS=$HOME/theos

          git clone --recursive https://github.com/theos/theos.git $THEOS

          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

          mkdir -p $THEOS/toolchain/linux

          git clone --depth=1 https://github.com/theos/llvm-project.git $THEOS/toolchain/linux/iphone

          chmod +x $THEOS/toolchain/linux/iphone/bin/* || true

          echo "===== Toolchain ====="
          ls -la $THEOS/toolchain/linux/iphone/bin

      - name: Install iPhoneOS SDK
        run: |
          export THEOS=$HOME/theos

          rm -rf $THEOS/sdks
          mkdir -p $THEOS/sdks

          git clone --depth=1 https://github.com/theos/sdks.git /tmp/theos-sdks

          find /tmp/theos-sdks -name "*.sdk" -type d -exec cp -R {} $THEOS/sdks/ \;

          echo "===== Installed SDKs ====="
          ls -la $THEOS/sdks

      - name: Build package
        run: |
          export THEOS=$HOME/theos
          make clean
          make package FINALPACKAGE=1

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: SB-CPU-Floating-deb
          path: packages/*.deb
